"""Añadir estado verificado_despacho a Bulto

Revision ID: 5f8ccac98335
Revises: bf0172bc07f7
Create Date: 2025-08-26 15:20:14.133752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8ccac98335'
down_revision = 'bf0172bc07f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado_despacho', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulto', schema=None) as batch_op:
        batch_op.drop_column('verificado_despacho')

    # ### end Alembic commands ###
