"""Añadir campo nota_bodega a Orden

Revision ID: 806f7c71c98d
Revises: a58479913601
Create Date: 2026-09-24 12:56:43.563006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806f7c71c98d'
down_revision = 'a58479913601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_bodega', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('nota_bodega')

    # ### end Alembic commands ###
