"""Añadir nota_entrega a Orden

Revision ID: 858799b10cf7
Revises: 5f8ccac98335
Create Date: 2025-08-28 18:43:50.315572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858799b10cf7'
down_revision = '5f8ccac98335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_entrega', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('nota_entrega')

    # ### end Alembic commands ###
