"""Añadir fecha_entrega_final a Orden

Revision ID: 9f95814c349d
Revises: d1ec91be0bd2
Create Date: 2025-09-02 19:10:19.501084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f95814c349d'
down_revision = 'd1ec91be0bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega_final', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('fecha_entrega_final')

    # ### end Alembic commands ###
