"""Añadir metodo_pago a Transaccion

Revision ID: a58479913601
Revises: 9f95814c349d
Create Date: 2025-09-05 19:12:55.112720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58479913601'
down_revision = '9f95814c349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=30), nullable=False, server_default='EFECTIVO'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
