"""Añadir fecha_finalizacion y guia_encomienda

Revision ID: ae5d487f717b
Revises: dce6a2ab129d
Create Date: 2025-07-21 12:06:08.896618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d487f717b'
down_revision = 'dce6a2ab129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_de_ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guia_encomienda', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_column('guia_encomienda')

    with op.batch_alter_table('hoja_de_ruta', schema=None) as batch_op:
        batch_op.drop_column('fecha_finalizacion')

    # ### end Alembic commands ###
