"""Añadir balance  de dineros recibidos por el conductor

Revision ID: bd7aa05b0dda
Revises: 
Create Date: 2025-07-21 19:41:40.403937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7aa05b0dda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hoja_de_ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('gastos_asignados', sa.Float(), nullable=False),
    sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_entrega', sa.String(length=20), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=True),
    sa.Column('nombre_transportista', sa.String(length=100), nullable=True),
    sa.Column('nombre_receptor', sa.String(length=100), nullable=True),
    sa.Column('id_receptor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_picking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operario_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_viaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoja_de_ruta_id', sa.Integer(), nullable=False),
    sa.Column('monto_gastado', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hoja_de_ruta_id'], ['hoja_de_ruta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_picking', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_picking', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_packing', sa.DateTime(), nullable=True),
    sa.Column('fecha_despacho', sa.DateTime(), nullable=True),
    sa.Column('packer_id', sa.Integer(), nullable=True),
    sa.Column('devolucion_confirmada', sa.Boolean(), nullable=False),
    sa.Column('hoja_de_ruta_id', sa.Integer(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('guia_encomienda', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.id'], ),
    sa.ForeignKeyConstraint(['hoja_de_ruta_id'], ['hoja_de_ruta.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_picking.id'], ),
    sa.ForeignKeyConstraint(['packer_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_table('bulto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('identificador_unico', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_unico')
    )
    op.create_table('item_orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('codigo_articulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion_articulo', sa.String(length=300), nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_recogida', sa.Integer(), nullable=False),
    sa.Column('cantidad_empacada', sa.Integer(), nullable=False),
    sa.Column('tiene_incidencia', sa.Boolean(), nullable=False),
    sa.Column('tipo_incidencia', sa.String(length=50), nullable=True),
    sa.Column('nota_incidencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoja_de_ruta_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('monto_recibido', sa.Float(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hoja_de_ruta_id'], ['hoja_de_ruta.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('tipo_incidencia', sa.String(length=50), nullable=False),
    sa.Column('nota_incidencia', sa.Text(), nullable=True),
    sa.Column('cantidad_solicitada_original', sa.Integer(), nullable=False),
    sa.Column('cantidad_recogida_reportada', sa.Integer(), nullable=False),
    sa.Column('item_orden_id', sa.Integer(), nullable=False),
    sa.Column('reportado_por_id', sa.Integer(), nullable=True),
    sa.Column('estado_resolucion', sa.String(length=20), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('resuelta_por_id', sa.Integer(), nullable=True),
    sa.Column('nota_resolucion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_orden_id'], ['item_orden.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reportado_por_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resuelta_por_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia_historial')
    op.drop_table('transaccion')
    op.drop_table('item_orden')
    op.drop_table('bulto')
    op.drop_table('orden')
    op.drop_table('gasto_viaje')
    op.drop_table('lote_picking')
    op.drop_table('hoja_de_ruta')
    op.drop_table('user')
    op.drop_table('destino')
    # ### end Alembic commands ###
