"""Añadir cantidad_unidades a Bulto para lotes

Revision ID: bf0172bc07f7
Revises: c731ccd319b3
Create Date: 2025-08-21 13:04:55.207696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0172bc07f7'
down_revision = 'c731ccd319b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_unidades', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulto', schema=None) as batch_op:
        batch_op.drop_column('cantidad_unidades')

    # ### end Alembic commands ###
