"""Hacer orden_id opcional en Transaccion para cobros

Revision ID: d1ec91be0bd2
Revises: 858799b10cf7
Create Date: 2025-09-02 18:14:43.951725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ec91be0bd2'
down_revision = '858799b10cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.alter_column('orden_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.alter_column('orden_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
